### ISSUE TITLE
snpStats

### ISSUE THREAD

**Issue by tuxette** [pneuvial/adjclust#22]
- [ ] check why NA's indices are only returned in the case of a class different from dgCMatrix
- [ ] check if a warning must be added when the diagonal is not (from scratch) equal to 1
- [ ] non uniform treatment for different types of input

**Comment by pneuvial** [comment]
> - [x]  check why NA's indices are only returned in the case of a class different from dgCMatrix

because in this case the input is assumed to be a matrix of genotypes (as now made more explicit in the documentation of `snpClust`. The LD is calculated internally and not returned, so we found useful to report the indices for the NA values in this specific case

> -[x] check if a warning must be added when the diagonal is not (from scratch) equal to 1

Added such a warning (only for dgCMatrix). Updated tests accordingly.

> -[x] non uniform treatment for different types of input

i.e. dgCMatrix is assumed to be a (LD) similarity matrix, while the other types of inputs are assumed to be a matrix of genotypes. Not changed (but clarified in the documentation of `snpClust`.
