### ISSUE TITLE
Diagonal elements in plotSim with dendrogram

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#38]
In the heatmaps generated by `plotSim` when a dendrogram is provided, the diagonal elements (= first row in the rotated heatmap) are twice smaller than the other ones. This is because the dendrogram hides half of them. 

```
set.seed(0xBEEF)
X <- matrix(rnorm(100), 5, 20)
D <- dist(X)
fit <- adjClust(D, type = "dissimilarity")
plotSim(D, type = "dissimilarity", dendro = fit)
```

(oops, there seems to be a reversal here and I don't understand why??)

**Comment by Zlamouche** [comment]
For the reversals : Contiguity Constrained HAC with heights defined as Variation of Within-Cluster Inertia can have reversals even for Euclidean data.

However, it seems that the result of Pierre's code and of "plot(fit)" are different. I think that it is because of horizontal positions of nodes (of the higher one to be more precise).

**Comment by tuxette** [comment]
Note on N's second remark: one is based on a dendrogram and the other on hclust. They can thus be different.

**Comment by tuxette** [comment]
ggplot2 version in commit 493461fb22dedeb5e6f4d8850f2b4907f6aa6898 solves this problem
