### ISSUE TITLE
User-defined breaks in 'plotSim'

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/adjclust#41]
Currently the argument 'breaks' of `plotSim` is the "number of breaks used to set colors from the palette."  In order to produce plots with the same color scale for different input matrices, it would be useful to allow a *sequence of breaks* to be provided as well.

**Comment by pneuvial** [comment]
@Zlamouche

**Comment by tuxette** [comment]
This issue is no more interesting after the transition to ggplot2 introduced in commit 9383f3ffa0f9175a0a56c1855a5efae6ab8359b1. If one wants to produce multiple matrices with the same scale, he can either use `facet_wrap` with a common `aes` or define breaks using `scale_fill_gradient` for instance.
